name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ./api
      - name: Run tests
        run: npm test
        working-directory: ./api
      - name: Build Backend Docker Image
        run: docker build -t ecommerce-backend ./api

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        working-directory: ./webapp
      - name: Run tests
        run: npm test
        working-directory: ./webapp
      - name: Build
        run: npm run build
        working-directory: ./webapp
      - name: Build Frontend Docker Image
        run: docker build -t ecommerce-frontend ./webapp